apiVersion: apps/v1
kind: Deployment
metadata:
  name: clicker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clicker
  template:
    metadata:
      labels:
        app: clicker
    spec:
      containers:
      - name: clicker-container
        image: clicker-app:latest
        ports:
        - containerPort: 80
